repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.14.0"
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
        exclude: ^docs/.*\.(py|rst)$ # Exclude docs/ directory for linting.
      # Run the formatter.
      - id: ruff-format
        exclude: ^docs/.*\.(py|rst)$ # Exclude docs/ directory for formatting.

  - repo: local
    hooks:
      # regenerate sync.py
      - id: generate_sync_facade
        name: Generate sync.py facade
        language: python
        entry: python tools/generate_sync_facade.py
        pass_filenames: false
        files: src/hassette/api/api.py
        stages:
          - pre-push

      # ensure codecov yaml is valid
      - id: check-codecov-yml
        name: Check codecov.yml validity
        language: system
        entry: curl --connect-timeout 10 --max-time 60 --fail --data-binary @./.github/codecov.yml https://codecov.io/validate
        types: [yaml]
        files: ^\.github/codecov\.yml$
        pass_filenames: false

      - id: check-missing-attribute
        name: Check for missing 'attributes' in State classes
        language: system
        entry: ./tools/check_for_missing_attribute.py
        pass_filenames: false
        stages:
          - pre-push

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        stages: [pre-push]
        exclude: ^(docs|scripts)/.*\.(py|rst)$ # Exclude docs/ and scripts/ directories for type checking.
