[hassette]
base_url = "http://localhost:8123"
app_dir = "hassette_apps"

[apps.hello_world]
filename = "main.py"
class_name = "MyApp"
enabled = true

[[apps.hello_world.config]]
greeting = "This is from the config file!"
