[hassette]
base_url = "http://localhost:8123"
app_dir = "src/hassette_apps"

[apps.hello_world]
filename = "hello_world.py"
class_name = "HelloWorld"
enabled = true

[[apps.hello_world.config]]
greeting = "Hello from Hassette!"
